import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  explanationSidebar: [
    'explanation/intro',
    'explanation/genesis',
    {
      type: 'category',
      label: 'The Method',
      items: [
        'explanation/method',
        'explanation/political-vision',
        'explanation/examples',
        'explanation/comparison',
        'explanation/personas',
      ],
    },
  ],
  referenceSidebar: [
    {
      type: 'category',
      label: 'Knowledge Graph',
      link: { type: 'doc', id: 'reference/knowledge-graph/overview' },
      items: [
        {
          type: 'category',
          label: 'Atoms',
          link: { type: 'doc', id: 'reference/knowledge-graph/atoms' },
          items: [
            { type: 'autogenerated', dirName: 'reference/knowledge-graph/atoms' },
          ],
        },
        {
          type: 'category',
          label: 'Crossings',
          link: { type: 'doc', id: 'reference/knowledge-graph/crossings' },
          items: [
            { type: 'autogenerated', dirName: 'reference/knowledge-graph/crossings' },
          ],
        },
      ],
    },
    'reference/catalogue',
    'reference/schema',
  ],
  howToSidebar: [
    'how-to/give-feedback',
    'how-to/send-listening-sheet',
    'how-to/message-listener',
  ],
};

export default sidebars;
