import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  methodSidebar: [
    'intro',
    'genesis',
    {
      type: 'category',
      label: 'The Method',
      items: [
        'method/core',
        'method/political-vision',
        'method/examples',
        'method/comparison',
        'method/personas',
      ],
    },
    {
      type: 'category',
      label: 'Catalogue',
      items: [
        'catalogue/misunderstandings',
      ],
    },
  ],
  knowledgeGraphSidebar: [
    'knowledge-graph/overview',
    {
      type: 'category',
      label: 'Atoms',
      link: { type: 'doc', id: 'knowledge-graph/atoms' },
      items: [
        { type: 'autogenerated', dirName: 'knowledge-graph/atoms' },
      ],
    },
    {
      type: 'category',
      label: 'Crossings',
      link: { type: 'doc', id: 'knowledge-graph/crossings' },
      items: [
        { type: 'autogenerated', dirName: 'knowledge-graph/crossings' },
      ],
    },
  ],
  contributeSidebar: [
    'contribute/commenting-guide',
    'contribute/listening-sheet',
    'contribute/message-listener',
    'contribute/rfc-atoms',
  ],
};

export default sidebars;
